### PR TITLE
fix(redirects): non-valid redirects will be redirected to homepage

### LINKED ISSUE #65: Avoid redirections to URLs outside of *.zalan.do domain after login
Taken from the penetration tests report performed by the Security team:

**Unvalidated Redirect URL**

In Login page, the url is vulnerable to unvalidated redirect URL:
https://sc-stage.norris.zalan.do/#/login?redirect=https:%2F%2Fwww.google.com

After login the page will be redirected to www.google.com

### PR DESCRIPTION
**Pull request by frontendherodk**
fixes #65 

Please make sure that you test the redirect throughly!

### CODE REVIEW

File: src/authentication-service.js [hunk 1]
```diff
@@ -441,10 +446,20 @@
...
-      return !!redirectionUrl && redirectionUrl.indexOf(domain) !== -1;
+      var urlParts = getUrlParts(decodedUrl);
+      var redirectUrl = getUrlQueryParts(urlParts.query, 'redirect');
+      if(angular.isUndefined(redirectUrl)) {
+        return true;
+      }
+      var decodedRedirectUrl = decodeURIComponent(redirectUrl);
+      var hostname = getUrlParts(decodedRedirectUrl, 'host');
+      return hostname.indexOf(domain) !== -1;
+
```
Comment (gregdeane) [inline src/authentication-service.js]: I'm able to get the code to redirect to a specific url. If I use the following url in localhost, it will redirect to my evil url:

`http://localhost:3333/#/login?redirect=http:%2F%2Fgoogle.localhost.evil.com`

I suppose it's just as likely in all environments (e.g. if `google.solutions.evil.com` is used in Prod, if `google.norris.evil.com` is used in Stage, etc.)

I could be wrong about my testing so please let me know if I'm missing something. If I am correct, I think more unit tests should be written to cover these cases. If I'm wrong, sorry! :)

**Comment by gregdeane** [comment]
It might be a good idea to run Stage locally via Docker so you can test that situation as well.

**Comment by gregdeane** [comment]
The branch for bugs should be `bugfix` rather than `bug`. No biggie, maybe for next time.

File: src/authentication-service.js (hunk 1 above)
Comment (frontendherodk) [inline src/authentication-service.js]: Nope you're absolutely right. I had to change the endsWith because Phantomjs doesn't support it and forgot to add a fallback solution for it.

**Comment by gregdeane** [comment]
Did you run on Stage from your local machine using Docker? If so, what were the results?
If not, you'll have missed one very important test.

**Comment by frontendherodk** [comment]
Running it with Stage won't change anything since it's only the endpoints changing. 
I did however test it, running from the dist folder and everything seems to work as well.

We will need to deploy to stage before you can test it with different environment.

**Comment by gregdeane** [comment]
👍

**Comment by frontendherodk** [comment]
👍
